root: true
parser: '@typescript-eslint/parser'

settings:
  import/resolver:
    node:
      extensions: [.js, .ts]

plugins:
  - '@typescript-eslint'
  - vitest
  - prettier

extends:
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:vitest/recommended

rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/camelcase': 'off'
  'prettier/prettier': 'error'
  'import/extensions': 'off'
  'import/prefer-default-export': 'off'
  'import/no-extraneous-dependencies': 'off'
ignorePatterns:
  - '**/node_modules/**'
  - '**/lib/**'
  - '**/doc/**'
  - '**/example/**'
  - '**/.deno/**'
