import {
  ArrowTypeValue,
  AspectTypeValue,
  BoolValue,
  ClusterModeValue,
  ColorValue,
  DirTypeValue,
  DoubleValue,
  EscStringValue,
  GraphvizValue,
  IntValue,
  LayerListValue,
  LayerRangeValue,
  LblStringValue,
  OutputModeValue,
  PackModeValue,
  PagedirValue,
  PointfListValue,
  PointfValue,
  PointValue,
  PortPosValue,
  QuadTypeValue,
  RankdirValue,
  RankTypeValue,
  RectValue,
  ShapeValue,
  SmoothTypeValue,
  StartTypeValue,
  StringValue,
  StyleValue,
  ViewPortValue,
} from '../valueType';

type Type<T> = new (...args: any[]) => T;

export const typeMap: Map<string, Type<GraphvizValue>> = new Map([
  ['Damping', DoubleValue],
  ['K', DoubleValue],
  ['URL', EscStringValue],
  ['area', DoubleValue],
  ['arrowhead', ArrowTypeValue],
  ['arrowsize', DoubleValue],
  ['arrowtail', ArrowTypeValue],
  ['aspect', AspectTypeValue],
  ['bb', RectValue],
  ['bgcolor', ColorValue],
  ['center', BoolValue],
  ['charset', StringValue],
  ['clusterrank', ClusterModeValue],
  ['color', ColorValue],
  ['colorscheme', StringValue],
  ['comment', StringValue],
  ['compound', BoolValue],
  ['concentrate', BoolValue],
  ['constraint', BoolValue],
  ['decorate', BoolValue],
  ['defaultdist', DoubleValue],
  ['dim', IntValue],
  ['dimen', IntValue],
  ['dir', DirTypeValue],
  ['diredgeconstraints', StringValue],
  ['distortion', DoubleValue],
  ['dpi', DoubleValue],
  ['edgeURL', EscStringValue],
  ['edgehref', EscStringValue],
  ['edgetarget', EscStringValue],
  ['edgetooltip', EscStringValue],
  ['epsilon', DoubleValue],
  ['esep', DoubleValue],
  ['fillcolor', ColorValue],
  ['fixedsize', BoolValue],
  ['fontcolor', ColorValue],
  ['fontname', StringValue],
  ['fontnames', StringValue],
  ['fontpath', StringValue],
  ['fontsize', DoubleValue],
  ['group', StringValue],
  ['headURL', EscStringValue],
  ['headclip', BoolValue],
  ['headhref', EscStringValue],
  ['headlabel', LblStringValue],
  ['headport', PortPosValue],
  ['headtarget', EscStringValue],
  ['headtooltip', EscStringValue],
  ['height', DoubleValue],
  ['href', EscStringValue],
  ['id', LblStringValue],
  ['image', StringValue],
  ['imagepath', StringValue],
  ['imagescale', StringValue],
  ['label', LblStringValue],
  ['labelURL', EscStringValue],
  ['labelangle', DoubleValue],
  ['labeldistance', DoubleValue],
  ['labelfloat', BoolValue],
  ['labelfontcolor', ColorValue],
  ['labelfontname', StringValue],
  ['labelfontsize', DoubleValue],
  ['labelhref', EscStringValue],
  ['labeljust', StringValue],
  ['labelloc', StringValue],
  ['labeltarget', EscStringValue],
  ['labeltooltip', EscStringValue],
  ['landscape', BoolValue],
  ['layer', LayerRangeValue],
  ['layerlistsep', StringValue],
  ['layers', LayerListValue],
  ['layerselect', LayerRangeValue],
  ['layersep', StringValue],
  ['layout', StringValue],
  ['len', DoubleValue],
  ['levels', IntValue],
  ['levelsgap', DoubleValue],
  ['lhead', StringValue],
  ['lheight', DoubleValue],
  ['lp', PointValue],
  ['ltail', StringValue],
  ['lwidth', DoubleValue],
  ['margin', PointfValue],
  ['maxiter', IntValue],
  ['mclimit', DoubleValue],
  ['mindist', DoubleValue],
  ['minlen', IntValue],
  ['mode', StringValue],
  ['model', StringValue],
  ['mosek', BoolValue],
  ['nodesep', DoubleValue],
  ['nojustify', BoolValue],
  ['normalize', BoolValue],
  ['nslimit', DoubleValue],
  ['nslimit1', DoubleValue],
  ['ordering', StringValue],
  ['orientation', StringValue],
  ['outputorder', OutputModeValue],
  ['overlap', StringValue],
  ['overlap_scaling', DoubleValue],
  ['pack', IntValue],
  ['packmode', PackModeValue],
  ['pad', PointfValue],
  ['page', PointfValue],
  ['pagedir', PagedirValue],
  ['pencolor', ColorValue],
  ['penwidth', DoubleValue],
  ['peripheries', IntValue],
  ['pin', BoolValue],
  ['pos', PointValue],
  ['quadtree', QuadTypeValue],
  ['quantum', DoubleValue],
  ['rank', RankTypeValue],
  ['rankdir', RankdirValue],
  ['ranksep', DoubleValue],
  ['ratio', StringValue],
  ['rects', RectValue],
  ['regular', BoolValue],
  ['remincross', BoolValue],
  ['repulsiveforce', DoubleValue],
  ['resolution', DoubleValue],
  ['root', StringValue],
  ['rotate', IntValue],
  ['rotation', DoubleValue],
  ['samehead', StringValue],
  ['sametail', StringValue],
  ['samplepoints', IntValue],
  ['scale', DoubleValue],
  ['searchsize', IntValue],
  ['sep', DoubleValue],
  ['shape', ShapeValue],
  ['shapefile', StringValue],
  ['showboxes', IntValue],
  ['sides', IntValue],
  ['size', PointfValue],
  ['skew', DoubleValue],
  ['smoothing', SmoothTypeValue],
  ['sortv', IntValue],
  ['splines', StringValue],
  ['start', StartTypeValue],
  ['style', StyleValue],
  ['stylesheet', StringValue],
  ['tail_lp', PointfValue],
  ['tailURL', EscStringValue],
  ['tailclip', BoolValue],
  ['tailhref', EscStringValue],
  ['taillabel', LblStringValue],
  ['tailport', PortPosValue],
  ['tailtarget', EscStringValue],
  ['tailtooltip', EscStringValue],
  ['target', EscStringValue],
  ['tooltip', EscStringValue],
  ['truecolor', BoolValue],
  ['vertices', PointfListValue],
  ['viewport', ViewPortValue],
  ['voro_margin', DoubleValue],
  ['weight', DoubleValue],
  ['width', DoubleValue],
  ['xlabel', LblStringValue],
  ['z', DoubleValue],
]);
