storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@ts-graphviz/*':
    access: $all
    publish: $all
  'ts-graphviz':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
log: { type: stdout, format: pretty, level: http }
