import type { $keywords } from '../utils/types/$keywords.js';
import type { $keywordsValidation } from '../utils/types/$keywordsValidation.js';

/**
 * Attribute types available for graph.
 * @group Attribute
 */
export type GraphAttributeKey = GraphAttributeKey.values; /** @hidden */

export namespace GraphAttributeKey {
  export type values = Exclude<keyof $values, keyof $exclude | symbol | number>;
  export interface $values
    extends $keywords<
      | 'Damping'
      | 'K'
      | 'URL'
      | '_background'
      | 'bb'
      | 'bgcolor'
      | 'center'
      | 'charset'
      | 'clusterrank'
      | 'colorscheme'
      | 'comment'
      | 'compound'
      | 'concentrate'
      | 'defaultdist'
      | 'dim'
      | 'dimen'
      | 'diredgeconstraints'
      | 'dpi'
      | 'epsilon'
      | 'esep'
      | 'fontcolor'
      | 'fontname'
      | 'fontnames'
      | 'fontpath'
      | 'fontsize'
      | 'forcelabels'
      | 'gradientangle'
      | 'href'
      | 'id'
      | 'imagepath'
      | 'inputscale'
      | 'label'
      | 'label_scheme'
      | 'labeljust'
      | 'labelloc'
      | 'landscape'
      | 'layerlistsep'
      | 'layers'
      | 'layerselect'
      | 'layersep'
      | 'layout'
      | 'levels'
      | 'levelsgap'
      | 'lheight'
      | 'lp'
      | 'lwidth'
      | 'margin'
      | 'maxiter'
      | 'mclimit'
      | 'mindist'
      | 'mode'
      | 'model'
      | 'mosek'
      | 'newrank'
      | 'nodesep'
      | 'nojustify'
      | 'normalize'
      | 'notranslate'
      | 'nslimit'
      | 'nslimit1'
      | 'ordering'
      | 'orientation'
      | 'outputorder'
      | 'overlap'
      | 'overlap_scaling'
      | 'overlap_shrink'
      | 'pack'
      | 'packmode'
      | 'pad'
      | 'page'
      | 'pagedir'
      | 'quadtree'
      | 'quantum'
      | 'rankdir'
      | 'ranksep'
      | 'ratio'
      | 'remincross'
      | 'repulsiveforce'
      | 'resolution'
      | 'root'
      | 'rotate'
      | 'rotation'
      | 'scale'
      | 'searchsize'
      | 'sep'
      | 'showboxes'
      | 'size'
      | 'smoothing'
      | 'sortv'
      | 'splines'
      | 'start'
      | 'style'
      | 'stylesheet'
      | 'target'
      | 'truecolor'
      | 'viewport'
      | 'voro_margin'
      | 'xdotversion'
      | 'class'
      | 'TBbalance'
    > {}
  export interface $exclude extends $keywordsValidation {}
}
