name: Generate Doc and Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: yarn --frozen-lockfile --ignore-optional
      env:
        CI: true
    - name: Generate doc
      run: yarn doc
      env:
        CI: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc
