name: Deploy static content to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-optional
        env:
          CI: true
      - name: Generate doc
        run: yarn doc
        env:
          CI: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
